// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwiIQQrF54qOHsV9J7Q14t92O2fFhvbAY',
    appId: '1:488725639720:web:e3c70e37c14b9041127b1d',
    messagingSenderId: '488725639720',
    projectId: 'sapid-labs',
    authDomain: 'sapid-labs.firebaseapp.com',
    storageBucket: 'sapid-labs.firebasestorage.app',
    measurementId: 'G-Y7R2MXGLT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYMxnxIhsMGEo9sclm38_P7hqkf7Ln_Y',
    appId: '1:488725639720:android:934324555f78630a127b1d',
    messagingSenderId: '488725639720',
    projectId: 'sapid-labs',
    storageBucket: 'sapid-labs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMMgUMfPP4r738L4vpW6FT7UxJjrtuKs',
    appId: '1:488725639720:ios:ebd90dde6a71ccfa127b1d',
    messagingSenderId: '488725639720',
    projectId: 'sapid-labs',
    storageBucket: 'sapid-labs.firebasestorage.app',
    iosBundleId: 'com.sapidlabs.slapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMMgUMfPP4r738L4vpW6FT7UxJjrtuKs',
    appId: '1:488725639720:ios:ebd90dde6a71ccfa127b1d',
    messagingSenderId: '488725639720',
    projectId: 'sapid-labs',
    storageBucket: 'sapid-labs.firebasestorage.app',
    iosBundleId: 'com.sapidlabs.slapp',
  );
}
