import 'package:flutter/material.dart';
import 'package:slapp/app/get_it.dart';
import 'package:slapp/app/router.dart';
import 'package:slapp/features/analytics/services/analytics_service.dart';
import 'package:slapp/features/auth/services/auth_service.dart';
import 'package:slapp/features/feedback/services/feedback_service.dart';
import 'package:slapp/features/onboarding/services/onboarding_service.dart';
import 'package:slapp/features/settings/services/settings_service.dart';
import 'package:slapp/features/shared/services/ai_service.dart';
import 'package:slapp/features/shared/services/crash/crash_service.dart';
import 'package:slapp/features/shared/services/permission_service.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:slapp/features/subscriptions/services/gate_service.dart';
import 'package:slapp/features/subscriptions/services/subscription_service.dart';

AIService get aiService => getIt.get<AIService>();
AnalyticsService get analyticsService => getIt.get<AnalyticsService>();
AppRouter get router => getIt.get<AppRouter>();
AuthService get authService => getIt.get<AuthService>();
CrashService get crashService => getIt.get<CrashService>();
FeedbackService get feedbackService => getIt.get<FeedbackService>();
GateService get gateService => getIt.get<GateService>();
OnboardingService get onboardingService => getIt.get<OnboardingService>();
SettingsService get settingsService => getIt.get<SettingsService>();
SharedPreferences get sharedPrefs => getIt.get<SharedPreferences>();
SubscriptionService get subscriptionService => getIt.get<SubscriptionService>();
PermissionService get permissionService => getIt.get<PermissionService>();
