// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_0MVMIdZjDWBi0wyehxri3-fjIEGSXg',
    appId: '1:16190533493:web:374c8ce71e2e601abaed3c',
    messagingSenderId: '16190533493',
    projectId: 'stack-fool',
    authDomain: 'stack-fool.firebaseapp.com',
    storageBucket: 'stack-fool.firebasestorage.app',
    measurementId: 'G-TEV4E8NMMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6B3CF6VwgabImcZiWoj2wv_eWnBJVZs',
    appId: '1:16190533493:android:508cae2ce16369babaed3c',
    messagingSenderId: '16190533493',
    projectId: 'stack-fool',
    storageBucket: 'stack-fool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB14bWP07rgBZRj48bElAkvY6vtv3aJnbo',
    appId: '1:16190533493:ios:14f8dbb6ba577a12baed3c',
    messagingSenderId: '16190533493',
    projectId: 'stack-fool',
    storageBucket: 'stack-fool.firebasestorage.app',
    iosClientId: '16190533493-rdj9k6catpdg5skmsfiodcojh873ht1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cotrFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB14bWP07rgBZRj48bElAkvY6vtv3aJnbo',
    appId: '1:16190533493:ios:14f8dbb6ba577a12baed3c',
    messagingSenderId: '16190533493',
    projectId: 'stack-fool',
    storageBucket: 'stack-fool.firebasestorage.app',
    iosClientId: '16190533493-rdj9k6catpdg5skmsfiodcojh873ht1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cotrFlutterApp',
  );

}